# Compiler
CXX = c++

# Compiler flags
CXXFLAGS = -Wall -Wextra -Werror -std=c++17
#CXXFLAGS += -fsanitize=address -fno-omit-frame-pointer -O1

# Target executable
TARGET = btc

# Source files
SRCS =	main.cpp 
# Object files

OBJS_Dir = objects
OBJS = $(addprefix $(Object.OBJS_Dir)/, $(SRCS:.cpp=.o))

# Default target
all: $(TARGET)

# Link the object files to create the executable
$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(OBJS)

# Compile source files into object files
$(OBJS_Dir)/%.o: %cpp | $(OBJS_Dir)
#%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@
$(OBJS_Dir)
	@echo "Creating $(OBJS_Dir) directory"
	@mkdir -p $(OBJS_Dir)

clean:
	rm -f $(OBJS) 

fclean: clean
	rm -f $(TARGET)
	rm -f *.txt

re: fclean all

# do not search for this files
.PHONY: all clean fclean re