# Compiler
CXX = c++

# Compiler flags
CXXFLAGS = -Wall -Wextra -Werror -std=c++17
#CXXFLAGS += -fsanitize=address -fno-omit-frame-pointer -O1

# Target executable
TARGET = btc

# Source files
SRCS =	main.cpp \
		BitcoinExchange.cpp \
		utilis.cpp \
		../color/color.cpp

# Object files

OBJS_Dir = objects
OBJS = $(addprefix $(OBJS_Dir)/, $(notdir $(SRCS:.cpp=.o)))

# Search path for source files
vpath %.cpp . ../color

# Default target
all: $(TARGET)

# Link the object files to create the executable
$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(OBJS)

$(OBJS_Dir):
	@echo "Creating $(OBJS_Dir) directory"
	@mkdir -p $(OBJS_Dir)

# Compile source files into object files
$(OBJS_Dir)/%.o: %.cpp | $(OBJS_Dir)
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) 

fclean: clean
	rm -f $(TARGET)
	rm -f *.txt
	rm -r -f objects
	rm -f DataBase/output.txt

re: fclean all

# do not search for this files
.PHONY: all clean fclean re